#! /bin/bash
cd `dirname $0`
. ../../../../../setup.conf


set -x 

## modified by youmin.ha@samsung.com
. ${TPLDIR}/base.tpl
set_vars

# if optins is clear or clean, delete all
if [[ "$1" == "clean" || "$1" == "clear" ]]; then
    rm -rf ${builddir}
    exit 0
fi


do_fetch
cd ${builddir}


$CC $CFLAGS -DFUSE -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DFUSE_USE_VERSION=25 -I$PREFIX/include -I$FACTORYFS/include -O2  -I. sqlfs.c fuse_main.c -o libsqlfs_mount -L$PREFIX/lib -L$FACTORYFS/lib -lpthread -lfuse -lsqlite3

/usr/bin/install -c libsqlfs_mount $PREFIX/bin/
