#!/bin/sh

# sqlfs mount(for configuration system)
if [ -f /opt/var/kdb/kdb_first_boot ]; then
   mv /opt/var/kdb/db /opt/var/kdb/db_tmp
   mkdir -p /opt/var/kdb/db
   /usr/bin/libsqlfs_mount -s -o nonempty -o default_permissions -o allow_other /opt/var/kdb/db
   sqlfs_txn_cmd /opt/var/kdb/db "chmod 777 /opt/var/kdb/db"
   sqlfs_txn_cmd /opt/var/kdb/db "mv /opt/var/kdb/db_tmp/* /opt/var/kdb/db/"
   rm -rf /opt/var/kdb/db_tmp /opt/var/kdb/kdb_first_boot
else
   /usr/bin/libsqlfs_mount -s -o nonempty -o default_permissions -o allow_other /opt/var/kdb/db
fi

