#!/bin/sh

#
# the normal service will only run this script when the firstboot file
# is in place. In that case, it will wait for this service to finish.
# But, since we need to SQL txn the template data in, we manually
# mount it here, and then unmount and exit.
#

# export path here in case systemd runs this without PATH being set.
export PATH=/bin:/usr/bin

if [ -f /opt/var/kdb/kdb_first_boot ]; then
   mv /opt/var/kdb/db /opt/var/kdb/db_tmp
   mkdir -p /opt/var/kdb/db
   libsqlfs_mount -s -o nonempty -o default_permissions -o allow_other /opt/var/kdb/db
   sqlfs_txn_cmd /opt/var/kdb/db "chmod 1777 /opt/var/kdb/db"
   sqlfs_txn_cmd /opt/var/kdb/db "cp -a /opt/var/kdb/db_tmp/* /opt/var/kdb/db/"
   for i in `find /opt/var/kdb/db_tmp/`; do
       f=`echo $i | sed "s|/opt/var/kdb/db_tmp|/opt/var/kdb/db|"`
       chmod --reference="$i" "$f"
   done
   rm -rf /opt/var/kdb/db_tmp /opt/var/kdb/kdb_first_boot
   umount /opt/var/kdb/db
fi

